# Generated by Django 4.2.4 on 2023-12-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_compra_items_compra_alter_inventario_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaC',
            field=models.DateField(max_length=20, verbose_name='Fecha de contratacion'),
        ),
    ]
